# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources.pasa as pa
import resources.salida as out
from designer.popupError import Ui_ErrMessage


class MyDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_ErrMessage()
        self.ui.setupUi(self)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.RLC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RLC.setFont(font)
        self.RLC.setAlignment(QtCore.Qt.AlignCenter)
        self.RLC.setObjectName("RLC")
        self.gridLayout.addWidget(self.RLC, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_filtro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_filtro.setFont(font)
        self.label_filtro.setObjectName("label_filtro")
        self.horizontalLayout_2.addWidget(self.label_filtro, 0, QtCore.Qt.AlignRight)
        self.comboFiltro = QtWidgets.QComboBox(self.centralwidget)
        self.comboFiltro.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboFiltro.setFont(font)
        self.comboFiltro.setObjectName("comboFiltro")
        self.comboFiltro.addItem("")
        self.comboFiltro.addItem("")
        self.comboFiltro.addItem("")
        self.comboFiltro.addItem("")
        self.horizontalLayout_2.addWidget(self.comboFiltro, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_R = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_R.setFont(font)
        self.label_R.setObjectName("label_R")
        self.horizontalLayout_12.addWidget(self.label_R, 0, QtCore.Qt.AlignRight)
        self.valor_R = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_R.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.valor_R.setFont(font)
        self.valor_R.setObjectName("valor_R")
        self.horizontalLayout_12.addWidget(self.valor_R, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_orden = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_orden.setFont(font)
        self.label_orden.setObjectName("label_orden")
        self.horizontalLayout.addWidget(self.label_orden, 0, QtCore.Qt.AlignHCenter)
        self.comboOrden = QtWidgets.QComboBox(self.centralwidget)
        self.comboOrden.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboOrden.setFont(font)
        self.comboOrden.setObjectName("comboOrden")
        self.comboOrden.addItem("")
        self.comboOrden.addItem("")
        self.horizontalLayout.addWidget(self.comboOrden, 0, QtCore.Qt.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_C = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_C.setFont(font)
        self.label_C.setObjectName("label_C")
        self.horizontalLayout_14.addWidget(self.label_C, 0, QtCore.Qt.AlignRight)
        self.valor_C = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_C.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.valor_C.setFont(font)
        self.valor_C.setObjectName("valor_C")
        self.horizontalLayout_14.addWidget(self.valor_C, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_14, 3, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_polos = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_polos.setFont(font)
        self.label_polos.setObjectName("label_polos")
        self.horizontalLayout_5.addWidget(self.label_polos, 0, QtCore.Qt.AlignRight)
        self.polos = QtWidgets.QLineEdit(self.centralwidget)
        self.polos.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.polos.setFont(font)
        self.polos.setObjectName("polos")
        self.horizontalLayout_5.addWidget(self.polos, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_L = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_L.setFont(font)
        self.label_L.setObjectName("label_L")
        self.horizontalLayout_13.addWidget(self.label_L, 0, QtCore.Qt.AlignRight)
        self.valor_L = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_L.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.valor_L.setFont(font)
        self.valor_L.setObjectName("valor_L")
        self.horizontalLayout_13.addWidget(self.valor_L, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_13, 2, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_filtro_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_filtro_2.setFont(font)
        self.label_filtro_2.setObjectName("label_filtro_2")
        self.horizontalLayout_6.addWidget(self.label_filtro_2, 0, QtCore.Qt.AlignRight)
        self.comboVo = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboVo.setFont(font)
        self.comboVo.setObjectName("comboVo")
        self.comboVo.addItem("")
        self.comboVo.addItem("")
        self.comboVo.addItem("")
        self.comboVo.addItem("")
        self.comboVo.addItem("")
        self.comboVo.addItem("")
        self.horizontalLayout_6.addWidget(self.comboVo, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_gain = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_gain.setFont(font)
        self.label_gain.setObjectName("label_gain")
        self.horizontalLayout_7.addWidget(self.label_gain, 0, QtCore.Qt.AlignRight)
        self.gain = QtWidgets.QLineEdit(self.centralwidget)
        self.gain.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gain.setFont(font)
        self.gain.setObjectName("gain")
        self.horizontalLayout_7.addWidget(self.gain, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ceros = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ceros.setFont(font)
        self.label_ceros.setObjectName("label_ceros")
        self.horizontalLayout_4.addWidget(self.label_ceros, 0, QtCore.Qt.AlignRight)
        self.ceros = QtWidgets.QLineEdit(self.centralwidget)
        self.ceros.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ceros.setFont(font)
        self.ceros.setObjectName("ceros")
        self.horizontalLayout_4.addWidget(self.ceros, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_in = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_in.setFont(font)
        self.label_in.setObjectName("label_in")
        self.horizontalLayout_10.addWidget(self.label_in)
        self.comboIn = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboIn.setFont(font)
        self.comboIn.setObjectName("comboIn")
        self.comboIn.addItem("")
        self.comboIn.addItem("")
        self.horizontalLayout_10.addWidget(self.comboIn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_ampfrec = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ampfrec.setFont(font)
        self.label_ampfrec.setObjectName("label_ampfrec")
        self.horizontalLayout_10.addWidget(self.label_ampfrec)
        self.amp_frec = QtWidgets.QLineEdit(self.centralwidget)
        self.amp_frec.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amp_frec.setFont(font)
        self.amp_frec.setObjectName("amp_frec")
        self.horizontalLayout_10.addWidget(self.amp_frec, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.button_bodeRLC = QtWidgets.QPushButton(self.centralwidget)
        self.button_bodeRLC.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_bodeRLC.setFont(font)
        self.button_bodeRLC.setObjectName("button_bodeRLC")
        self.gridLayout.addWidget(self.button_bodeRLC, 5, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_frec = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_frec.setFont(font)
        self.label_frec.setObjectName("label_frec")
        self.horizontalLayout_3.addWidget(self.label_frec, 0, QtCore.Qt.AlignRight)
        self.frec_corte = QtWidgets.QLineEdit(self.centralwidget)
        self.frec_corte.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frec_corte.setFont(font)
        self.frec_corte.setObjectName("frec_corte")
        self.horizontalLayout_3.addWidget(self.frec_corte, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.button_bode = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_bode.setFont(font)
        self.button_bode.setObjectName("button_bode")
        self.horizontalLayout_11.addWidget(self.button_bode)
        self.button_out = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_out.setFont(font)
        self.button_out.setObjectName("button_out")
        self.horizontalLayout_11.addWidget(self.button_out)
        self.gridLayout.addLayout(self.horizontalLayout_11, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.comboOrden.currentTextChanged.connect(self.updateOrden)
        self.button_bode.clicked.connect(self.bodeClicked)
        self.comboIn.activated.connect(self.updateIn)
        self.comboFiltro.activated.connect(self.updateZP)
        self.button_out.clicked.connect(self.salidaClicked)
        self.button_bodeRLC.clicked.connect(self.bodeRLC)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bode App"))
        self.RLC.setText(_translate("MainWindow", "RLC"))
        self.label_filtro.setText(_translate("MainWindow", "Tipo de filtro"))
        self.comboFiltro.setItemText(0, _translate("MainWindow", "Pasa altos"))
        self.comboFiltro.setItemText(1, _translate("MainWindow", "Pasa bajos"))
        self.comboFiltro.setItemText(2, _translate("MainWindow", "Pasa todo"))
        self.comboFiltro.setItemText(3, _translate("MainWindow", "Personalizado"))
        self.label_R.setText(_translate("MainWindow", "R"))
        self.label_orden.setText(_translate("MainWindow", "Orden"))
        self.comboOrden.setItemText(0, _translate("MainWindow", "1"))
        self.comboOrden.setItemText(1, _translate("MainWindow", "2"))
        self.label_C.setText(_translate("MainWindow", "C"))
        self.label_polos.setText(_translate("MainWindow", "--"))
        self.label_L.setText(_translate("MainWindow", "L"))
        self.label_filtro_2.setText(_translate("MainWindow", "Vout (+ a -)"))
        self.comboVo.setItemText(0, _translate("MainWindow", "1-2"))
        self.comboVo.setItemText(1, _translate("MainWindow", "2-1"))
        self.comboVo.setItemText(2, _translate("MainWindow", "2-3"))
        self.comboVo.setItemText(3, _translate("MainWindow", "3-2"))
        self.comboVo.setItemText(4, _translate("MainWindow", "3-4"))
        self.comboVo.setItemText(5, _translate("MainWindow", "4-3"))
        self.label_gain.setText(_translate("MainWindow", "Ganancia"))
        self.gain.setText(_translate("MainWindow", "1"))
        self.label_ceros.setText(_translate("MainWindow", "--"))
        self.label_in.setText(_translate("MainWindow", "Entrada"))
        self.comboIn.setItemText(0, _translate("MainWindow", "Escalon"))
        self.comboIn.setItemText(1, _translate("MainWindow", "Seno"))
        self.label_ampfrec.setText(_translate("MainWindow", "Amplitud"))
        self.amp_frec.setText(_translate("MainWindow", "1"))
        self.button_bodeRLC.setText(_translate("MainWindow", "Bode (RLC)"))
        self.label_frec.setText(_translate("MainWindow", "Frecuencia de corte"))
        self.frec_corte.setText(_translate("MainWindow", "1000"))
        self.button_bode.setText(_translate("MainWindow", "Bode"))
        self.button_out.setText(_translate("MainWindow", "Bode+salida"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

    def showError(self):
        self.myDialog = MyDialog()
        self.myDialog.show()
    """
    Funciones RLC
    """
    def bodeRLC(self):
        R=pa.parseSci(self.valor_R.text())
        L=pa.parseSci(self.valor_L.text())
        C=pa.parseSci(self.valor_C.text())
        v0=self.comboVo.currentText()
        if R=="E" or L=="E" or C=="E":
            self.showError()
            return
        if v0=="1-2" or v0=="2-1":
            v="R"
            if v0=="2-1":
                R=-R
        elif v0=="2-3" or v0=="3-2":
            v="L"
            if v0=="3-2":
                L=-L
        elif v0 == "3-4" or v0 == "4-3":
            v = "C"
            if v0=="4-3":
                C=-C
        pa.RLC(R, L, C, v, v0)
        return

    """
    Funciones Bode
    """
    def bodeClicked(self):

        if not bool(self.gain.text()):
            max_gain=1
        else:
            max_gain=pa.parseArray(self.gain.text())


        fc=pa.parseArray(self.frec_corte.text())
        if fc=="E" or max_gain=="E":
            self.showError()
            return
        else:
            ord=int(self.comboOrden.currentText())
            fil=self.comboFiltro.currentText()
            if fil=="Pasa altos":
                if ord==1:
                    z=0
                    p=-fc
                else:
                    z=[0,0]
                    p=[-fc, 0.5]
                num, den=pa.pasaAltos(ord, z, p, max_gain)
            elif fil=="Pasa bajos":
                if ord == 1:
                    p = -fc
                    z = 0
                else:
                    z = [0, 0]
                    p = [-fc, 0.5]

                num, den=pa.pasaBajos(ord, z, p, max_gain)
            elif fil=="Pasa todo":
                if ord==1:
                    z=1
                    p=-fc
                else:
                    z=[-fc, 0.5]
                    p=z
                num, den=pa.pasaTodo(ord, z, p, max_gain)
            elif fil == "Personalizado":
                if not bool(self.ceros.text()):
                    z="E"
                else:
                    z = pa.parseArray(self.ceros.text())
                if not bool(self.polos.text()):
                    p = "E"
                else:
                    p = pa.parseArray(self.polos.text())

                if z == "E" or p == "E":
                    self.showError()
                    return
                if ord==2:
                    num, den=pa.pasalgo2(z, p, max_gain)
                else:
                    num, den=pa.pasalgo1(z, p, max_gain)
            elif fil=="Pasa banda":
                p=[fc, 1]
                z=[0, 0]
                num, den=pa.pasaBanda(z, p, max_gain)
            elif fil == "Notch":
                p = [fc, 1]
                z = [fc, 0]
                num, den=pa.notch(z, p, max_gain)
        return num, den

    def salidaClicked(self):
        y=self.bodeClicked()
        amp = pa.parseArray(self.amp_frec.text())
        if y==None or amp=="E":
            self.showError()
            return
        else:
            num=y[0]
            den=y[1]
        tipo=self.comboIn.currentText()

        flag=out.salida(tipo, amp, num, den)
        if flag=="E":
            self.showError()
            return

    """
    Update de labels
    """
    def updateOrden(self):
        orden=self.comboOrden.currentText()
        self.comboFiltro.clear()

        self.comboFiltro.addItem("Pasa altos")
        self.comboFiltro.addItem("Pasa bajos")
        self.comboFiltro.addItem("Pasa todo")
        self.comboFiltro.addItem("Personalizado")

        if orden == "2":
            self.comboFiltro.addItem("Pasa banda")
            self.comboFiltro.addItem("Notch")

        self.updateZP()

    def updateIn(self):
        entrada=self.comboIn.currentText()
        if entrada == "Escalon":
            self.label_ampfrec.setText("Amplitud")
        else:
            self.label_ampfrec.setText("[Amp, Frec]")

    def updateZP(self):
        fil = self.comboFiltro.currentText()
        ord = self.comboOrden.currentText()
        if fil != "Personalizado":
            self.label_ceros.setText("--")
            self.label_polos.setText("--")
            self.label_frec.setText("Frecuencia de corte")
        else:
            if ord == "2":
                self.label_ceros.setText(
                    "Ceros ["u'\N{GREEK SMALL LETTER OMEGA}\N{SUBSCRIPT ZERO}'", \N{GREEK SMALL LETTER XI}]")
                self.label_polos.setText(
                    "Polos ["u'\N{GREEK SMALL LETTER OMEGA}\N{SUBSCRIPT ZERO}'", \N{GREEK SMALL LETTER XI}]")
            else:
                self.label_ceros.setText("Cero")
                self.label_polos.setText("Polo")
                self.label_frec.setText("--")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
