# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popupError.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrMessage(object):
    def setupUi(self, ErrMessage):
        ErrMessage.setObjectName("ErrMessage")
        ErrMessage.resize(261, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(ErrMessage.sizePolicy().hasHeightForWidth())
        ErrMessage.setSizePolicy(sizePolicy)
        ErrMessage.setMaximumSize(QtCore.QSize(261, 100))
        self.gridLayout = QtWidgets.QGridLayout(ErrMessage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_error = QtWidgets.QLabel(ErrMessage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_error.setFont(font)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.gridLayout.addWidget(self.label_error, 0, 0, 1, 1)

        self.retranslateUi(ErrMessage)
        QtCore.QMetaObject.connectSlotsByName(ErrMessage)

    def retranslateUi(self, ErrMessage):
        _translate = QtCore.QCoreApplication.translate
        ErrMessage.setWindowTitle(_translate("ErrMessage", "Error"))
        self.label_error.setText(_translate("ErrMessage", "El texto ingresado es inválido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrMessage = QtWidgets.QDialog()
    ui = Ui_ErrMessage()
    ui.setupUi(ErrMessage)
    ErrMessage.show()
    sys.exit(app.exec_())
